name: jenkins-ssh-slave
version: 0.0.1
appVersion: latest
description: A Jenkins slave using SSH to establish connection.
icon: https://d33np9n32j53g7.cloudfront.net/assets/stacks/jenkins/img/jenkins-stack-220x234-ef694d84df5715062481cb67aa2b853c.png
keywords:
- development
- continous integration
home: https://jenkins.io/
sources:
- https://github.com/jenkinsci/docker-ssh-slave.git
maintainers:
- name: Thought Gang GmbH, Hamburg
  email: support@thoughtgang.de
engine: gotpl
